export const sampleQuestions = [
  // ===== 生物分野 =====
  {
    field: '生物',
    unit: '細胞と生物',
    question: '細胞の中で、呼吸（エネルギーをつくる）を行う場所はどこか？',
    type: 'choice' as const,
    choices: ['核', 'ミトコンドリア', '葉緑体', '細胞壁'],
    answer: 'ミトコンドリア',
    explanation: 'ミトコンドリアは細胞呼吸を行い、ATPというエネルギーを作り出す細胞小器官です。',
    grade: '中2',
  },
  {
    field: '生物',
    unit: '細胞と生物',
    question: '光合成を行う細胞小器官の名前は何か？',
    type: 'choice' as const,
    choices: ['ミトコンドリア', '核', '葉緑体', '液胞'],
    answer: '葉緑体',
    explanation: '葉緑体は光合成を行い、光エネルギーを使ってデンプンなどの有機物を合成します。',
    grade: '中2',
  },
  {
    field: '生物',
    unit: '遺伝',
    question: 'エンドウ豆の実験で遺伝の法則を発見した科学者は誰か？',
    type: 'choice' as const,
    choices: ['ダーウィン', 'メンデル', 'パスツール', 'フック'],
    answer: 'メンデル',
    explanation: 'グレゴール・メンデルはエンドウ豆を使った実験で、優性の法則・分離の法則・独立の法則を発見しました。',
    grade: '中3',
  },
  {
    field: '生物',
    unit: '遺伝',
    question: '純系の丸い種子(AA)と純系のしわのある種子(aa)を交配したとき、F1(第一代)の種子の形質はどうなるか？',
    type: 'choice' as const,
    choices: ['すべてしわ', 'すべて丸', '丸としわが1:1', '丸としわが3:1'],
    answer: 'すべて丸',
    explanation: 'AAとaaを交配するとすべてAaになります。丸が優性なので、F1はすべて丸になります。',
    grade: '中3',
  },
  {
    field: '生物',
    unit: '消化と吸収',
    question: 'タンパク質を分解する消化酵素はどれか？',
    type: 'choice' as const,
    choices: ['アミラーゼ', 'リパーゼ', 'ペプシン', 'マルターゼ'],
    answer: 'ペプシン',
    explanation: 'ペプシンは胃液に含まれるタンパク質分解酵素です。アミラーゼはデンプン、リパーゼは脂肪を分解します。',
    grade: '中2',
  },
  {
    field: '生物',
    unit: '神経',
    question: '反射とは何か、簡単に説明しなさい。',
    type: 'text' as const,
    choices: null,
    answer: '刺激に対して意識とは無関係に起こる反応',
    explanation: '反射は脊髄などで命令が出るため、大脳を経由せず素早く反応できます。',
    grade: '中2',
  },

  // ===== 化学分野 =====
  {
    field: '化学',
    unit: '原子と分子',
    question: '水の化学式はどれか？',
    type: 'choice' as const,
    choices: ['H₂O₂', 'HO', 'H₂O', 'H₃O'],
    answer: 'H₂O',
    explanation: '水は水素原子2個と酸素原子1個が結びついた分子です。',
    grade: '中2',
  },
  {
    field: '化学',
    unit: '原子と分子',
    question: '食塩(塩化ナトリウム)の化学式はどれか？',
    type: 'choice' as const,
    choices: ['NaCl', 'KCl', 'NaOH', 'CaCl₂'],
    answer: 'NaCl',
    explanation: '塩化ナトリウムはナトリウム(Na)と塩素(Cl)が1:1で結びついたイオン結晶です。',
    grade: '中2',
  },
  {
    field: '化学',
    unit: '化学変化',
    question: '鉄と硫黄を加熱すると何ができるか？',
    type: 'choice' as const,
    choices: ['酸化鉄', '硫化鉄', '塩化鉄', '炭酸鉄'],
    answer: '硫化鉄',
    explanation: 'Fe + S → FeS（硫化鉄）。元の鉄や硫黄とは全く異なる性質を持つ新物質が生成されます。',
    grade: '中2',
  },
  {
    field: '化学',
    unit: 'イオン',
    question: '塩酸(HCl)が水に溶けたとき、電離式として正しいものはどれか？',
    type: 'choice' as const,
    choices: ['HCl → H⁺ + Cl⁻', 'HCl → H⁻ + Cl⁺', 'HCl → 2H + Cl', 'HCl → H₂ + Cl₂'],
    answer: 'HCl → H⁺ + Cl⁻',
    explanation: '塩酸は水中で水素イオン(H⁺)と塩化物イオン(Cl⁻)に完全電離します。',
    grade: '中3',
  },
  {
    field: '化学',
    unit: 'イオン',
    question: '酸とアルカリが反応して水と塩ができる反応を何というか？',
    type: 'choice' as const,
    choices: ['酸化', '還元', '中和', '電離'],
    answer: '中和',
    explanation: '酸のH⁺とアルカリのOH⁻が反応してH₂Oが生成される反応を中和といいます。',
    grade: '中3',
  },
  {
    field: '化学',
    unit: '酸化と還元',
    question: '銅を加熱したときの変化を化学反応式で書きなさい。',
    type: 'text' as const,
    choices: null,
    answer: '2Cu + O₂ → 2CuO',
    explanation: '銅が酸素と結びついて酸化銅(CuO)になります。質量は増加します。',
    grade: '中2',
  },

  // ===== 物理分野 =====
  {
    field: '物理',
    unit: '力と運動',
    question: '質量10kgの物体にはたらく重力の大きさは何Nか？（重力加速度を10m/s²とする）',
    type: 'choice' as const,
    choices: ['1N', '10N', '100N', '1000N'],
    answer: '100N',
    explanation: '重力(N) = 質量(kg) × 重力加速度(m/s²) = 10 × 10 = 100N',
    grade: '中3',
  },
  {
    field: '物理',
    unit: '電気',
    question: '電圧6V、電流2Aのとき、電力は何Wか？',
    type: 'choice' as const,
    choices: ['3W', '4W', '8W', '12W'],
    answer: '12W',
    explanation: '電力(W) = 電圧(V) × 電流(A) = 6 × 2 = 12W',
    grade: '中2',
  },
  {
    field: '物理',
    unit: '電気',
    question: 'オームの法則の式として正しいものはどれか？',
    type: 'choice' as const,
    choices: ['V = I × R', 'V = I / R', 'V = I + R', 'V = I - R'],
    answer: 'V = I × R',
    explanation: '電圧(V) = 電流(I) × 抵抗(R)。これをオームの法則といいます。',
    grade: '中2',
  },
  {
    field: '物理',
    unit: '力と運動',
    question: '物体に力がはたらいていない、またはつりあっているとき、物体はどんな運動をするか？',
    type: 'choice' as const,
    choices: ['加速する', '減速する', '等速直線運動を続ける', '円運動する'],
    answer: '等速直線運動を続ける',
    explanation: 'ニュートンの第1法則（慣性の法則）です。静止している物体は静止し続け、動いている物体は等速直線運動を続けます。',
    grade: '中3',
  },
  {
    field: '物理',
    unit: '波と音',
    question: '音の速さは約何m/sか？（気温15℃の空気中）',
    type: 'choice' as const,
    choices: ['約34m/s', '約170m/s', '約340m/s', '約3400m/s'],
    answer: '約340m/s',
    explanation: '音は空気中を約340m/sで伝わります。光の速さ(約30万km/s)より圧倒的に遅いです。',
    grade: '中1',
  },
  {
    field: '物理',
    unit: 'エネルギー',
    question: '位置エネルギーと運動エネルギーの和を何というか？',
    type: 'text' as const,
    choices: null,
    answer: '力学的エネルギー',
    explanation: '摩擦や空気抵抗がなければ、力学的エネルギーは保存されます（力学的エネルギー保存の法則）。',
    grade: '中3',
  },

  // ===== 地学分野 =====
  {
    field: '地学',
    unit: '地震',
    question: '地震の揺れが最初に伝わる小さな揺れを何というか？',
    type: 'choice' as const,
    choices: ['主要動', '初期微動', '余震', '本震'],
    answer: '初期微動',
    explanation: '地震波のP波が先に到達して起こる小さな揺れを初期微動といいます。後からS波が来ると大きな揺れ（主要動）になります。',
    grade: '中1',
  },
  {
    field: '地学',
    unit: '地震',
    question: '震源からの距離が遠いほど、初期微動継続時間はどうなるか？',
    type: 'choice' as const,
    choices: ['短くなる', '変わらない', '長くなる', '最初は長く後で短くなる'],
    answer: '長くなる',
    explanation: 'P波とS波の速さの差が距離とともに蓄積されるため、震源から遠いほど初期微動継続時間は長くなります。',
    grade: '中1',
  },
  {
    field: '地学',
    unit: '天気',
    question: '日本付近で低気圧はどちらの方向に風が吹き込むか？',
    type: 'choice' as const,
    choices: ['時計回り', '反時計回り', '中心から外へ', 'まっすぐ中心へ'],
    answer: '反時計回り',
    explanation: '北半球では低気圧に反時計回りに風が吹き込みます（コリオリの力の影響）。高気圧は時計回りに吹き出します。',
    grade: '中2',
  },
  {
    field: '地学',
    unit: '天気',
    question: '前線のうち、暖気が寒気の上にゆっくり乗り上げて進む前線を何というか？',
    type: 'choice' as const,
    choices: ['寒冷前線', '温暖前線', '停滞前線', '閉塞前線'],
    answer: '温暖前線',
    explanation: '温暖前線は暖気が寒気の上にゆっくり乗り上げ、広い範囲に穏やかな雨をもたらします。',
    grade: '中2',
  },
  {
    field: '地学',
    unit: '宇宙',
    question: '地球から最も近い恒星は何か？',
    type: 'choice' as const,
    choices: ['シリウス', '太陽', 'プロキシマ・ケンタウリ', 'ベガ'],
    answer: '太陽',
    explanation: '太陽は地球から約1億5000万kmの距離にある恒星です。次に近い恒星はプロキシマ・ケンタウリ（約4.2光年）です。',
    grade: '中3',
  },
  {
    field: '地学',
    unit: '岩石と地層',
    question: 'マグマが地表に噴き出して急速に冷えてできた岩石を何というか？',
    type: 'choice' as const,
    choices: ['深成岩', '堆積岩', '変成岩', '火山岩'],
    answer: '火山岩',
    explanation: '火山岩はマグマが地表や地表付近で急冷してできた岩石で、斑晶と石基からなる斑状組織を持ちます。',
    grade: '中1',
  },
]
